
# INPUT FILES
proffaqua.input.file=OrgNrs.txt

# OUTPUT FILES
output.file=OrgNrReport.csv

# EXCEL
excel.file=KI-Updated.xlsx

# UNTOUCHED = leave empty CSV values unchanged in Excel (default)
# CLEAR = clear Excel cells and highlight when CSV value is empty
empty.value.processing=UNTOUCHED

# PROVIDER
request.delay.ms=1500
retry.count=3
provider=PROFF_WEB

# ACCOUNTING DETAILS
accounting.info.file=config.accountinginfo
