output.file=CompanyFinancials.csv
aqua.output.file=AquacultureCapacity.csv
input.file=OrgNrs.txt
excel.file=ORGINAL_COPY.xlsx
request.delay.ms=1500
retry.count=3
provider=PROFF_WEB

accounting.info.file=config.accountinginfo
