
# INPUT FILES
proffaqua.input.file=OrgNrs.txt

# OUTPUT FILES
output.file=OrgNrReport.csv

# EXCEL
excel.file=ORGINAL_COPY.xlsx

# PROVIDER
request.delay.ms=1500
retry.count=3
provider=PROFF_WEB

# ACCOUNTING DETAILS
accounting.info.file=config.accountinginfo
